### PR TITLE
Milestone 5

### PR DESCRIPTION
**Pull request by JayKowski**
MIlestone containing some additional features such as :- 
  1.) Accepting friend requests
  2.) unfriending friends
  3.) Rejecting friend requests
  4.) Sending friend requests
  5.) Added tests
Also, linted the above features implemented
ready for review!

### CODE REVIEW

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello,

Thanks for the improvements done!!
However, there are some requirements that are not yet met

1. According to [that](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png), Posts timeline includes posts written by logged-in user and their friends which is not the case according to your `timeline_posts` method

2. According to [that screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png), he should have a button to invite user to friendship also on single user page.

3. There are no integration tests in your project. Please, write some for the friendship requirements.

Kindly make the suggested changes and submit a new code review request.
Thanks

Mael FOSSO

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

Hi team!  :wave: 

The changes required from my colleague hasn't been implemented.

 - On a logged-in user's timeline, I am only able to see the friend's post.
 - There are no feature or integration tests.
 - The link for inviting friends should be implemented as a button.

These changes I requested are referenced from Mael Fosso's code review.

After effecting the changes, submit another form for a code review.

Best,

Henry.

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello, Thank you for the improvements done!!

However there are still some requirements that are not met

1. There is no button for sending a friendship request to an user from his single page that from `user/:id`. It indicated [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png) has a requirement

2. There are no integrations tests. Your `spec/features/friendshps_spec.rb` is empty.

Kindly make those changes and submit a new code review request.
Thanks

Mael FOSSO

**Comment by samgaco** [comment]
all the changes implemented, you can continue :+1: 

-------------------

* ###### STATUS OF THE MILESTONE: APPROVED :heavy_check_mark:

**Pull request merged**
